Testnet userid page layout fixes for small screens
iron-fish/website-testnet pull request #170
Opened 2022-01-20 23:35 UTC by manjash

## Summary
For small screens:
- Font size changed for graffiti and summary numbers
- Fish icon is smaller
- Positioning of the page start is fixed
- Large graffiti strings now break
- Fixed horizontal scroll issue 

https://github.com/iron-fish/website-testnet/issues/135

## Testing Plan
Used mock data in apiClient/client.ts.
Tested on desktop Chrome  browser (responsive regime, several mobile devices) and with Safari on iPhone 13 (landscape and portrait orientations).

## Breaking Change

Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

```
[ ] Yes
```

2022-01-22 01:57 UTC, NullSoldier commented
Looks like this fails to build.

2022-01-24 22:44 UTC, brekk commented
@manjash Looks like there's an area where you copy-pasted raw SVG (?), you might need to change `class` to `className`. You can also run the linting locally and that should show you the issue as well. `nps lint` / see `package-scripts.js` for more.

2022-02-11 01:28 UTC, manjash commented
@brekk Hey, thank you very much for the hints :)

2022-02-12 22:07 UTC, manjash commented
@dguenther Hey, is this a problem on my end again?

2022-02-12 22:08 UTC, dguenther commented
Nope, I'm just looking through this now. Thanks for asking though!

2022-02-12 22:33 UTC, dguenther requested changes
Left a few change requests -- In general, I'd say this PR should aim for the desktop / 1920x1080 size to look exactly the same as it does now. (aside from copy changes like "All Time Rank" to "Rank"). It'll help if you try to make the PR as small as possible, for example, just adding a breakpoint for smaller header text along with `break-all` will solve most of the small screen issues.

2022-02-12 22:33 UTC, dguenther commented on components/OffsetBorder/Box.tsx
> +        `mr-5`,
This margin value is specifically chosen to offset the `-right-2.5` values in the enclosed div. We should leave this as it was at `mr-2.5`

2022-02-18 22:58 UTC, manjash commented on pages/users/[id].tsx
> +            <div className="px-7 pt-7 md:px-24 md:pt-16 pb-12">
I hope you don't mind that I left 2 different sets of paddings (fixed the pt for desktop though), it's more aligned with the designs (and saves space on mobile)

2022-02-18 23:04 UTC, manjash commented on pages/users/[id].tsx
> +                        <th className="font-normal pr-2">POINTS</th>
Beautification mostly, it was almost spaceless on mobile (POINTSDETAILS)

2022-03-09 00:37 UTC, dguenther commented
We ended up implementing this with some additional feedback from our designer and deployed it out recently -- Sorry for failing to respond to your comments sooner here. I'm going to close this PR, but you're still welcome to submit it for testnet credit if you haven't already!

2022-03-09 00:37 UTC, closed without merging