Phase 2
iron-fish/website-testnet pull request #219
Opened 2022-04-04 17:22 UTC by brekk

## Summary

WIP

## Testing Plan

👀 

## Breaking Change

Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

```
[ ] Yes
[x] No
```

2022-04-05 22:03 UTC, dguenther requested changes
One more thing that I couldn't attach directly to a line of code:

* Does the cypress failed screenshot need to be removed?

2022-04-05 22:03 UTC, dguenther commented on pages/about.tsx
> +          text="Get ready to claim your share of 315,000 $IRON! To make Phase 2 fair, we’ve removed weekly limits on point earnings. We’re also introducing a new leaderboard; but don’t worry, all acc
I think somewhere else this "315,000" number was computed from the phase + pool data, should we do that here too?

2022-04-05 23:06 UTC, brekk commented
> * Does the cypress failed screenshot need to be removed?

I didn't think it needed to be part of the codebase -- I think one of the integrations has a config which generates screenshots but I figured it would be ok to keep it out of the codebase for the future.

2022-04-05 23:06 UTC, brekk commented
@dguenther Thanks for the thorough feedback -- I've addressed everything and I think it should be cleaner now.

2022-04-06 05:20 UTC, AmberKiso commented
Looking forward to this being officially announced!

2022-04-06 13:53 UTC, dguenther approved these changes
Nice, thanks for fixing those up!

2022-04-06 16:22 UTC, merged